### ISSUE TITLE
Adding images to quiz

### ISSUE THREAD

**Issue by raghav-kukreti** [Polymer/topeka#4]
How does one add an image to a corresponding question?
The questions are all written in JSON.
Is there a way of accomplishing that?

**Comment by dev3320770** [comment]
@raghav-kukreti try this 

In the JSON file where you find the questions add another name and value (eg, "pic":"www.example.com/me.jpeg") then in topeka-elements directory u will find a html file name topeka-quizzes, open it and look for this line 

        <div class="question" flex cross-fade-delayed>{{quiz.question}}</div>

duplicate it and rename questions to name (eg, {{quiz.pic}}) that you created and test it.
